### ISSUE TITLE
Ship the source code and zig compiler

### ISSUE THREAD

**Issue by IntegratedQuantum** [PixelGuys/Cubyz#118]
This should be possible with the Zig compiler, but I'm not 100% sure if it would work on windows (if a visual studio installation is needed, that would be problematic).

But this would be advantageous in so many ways:
- Compiling on the user's machine would allow compiling for their CPU, so people with avx or avx512 would get a performance boost.
- Exposing the source code would allow for a community maintained modding environment, like in minecraft (which also exposes it's source code due to java decompilation)
- This would make it easier for me to debug the game on other peoples computers, because I don't need to compile the game for them 100 times. Additionally people could run the game in debug mode directly without requiring a separate executable.
- This would make it easier to publish a release version, since I wouldn't need to compile the game for many different operating systems.
- People can download development versions to test new features without needing to wait.
- Although that probably won't affect many people, this would make it easier for people who never programmed before to get into programming, because they wouldn't need to install tons of stuff (that's a step I failed on when I started to learn about programming)

It does come at some cost though:
- First game launch will take more time due compiling the game
- Higher disk space usage due to the compiler and its caching

### Requirements
- [x] #104
- [x] #117

**Comment by IntegratedQuantum** [comment]
This is basically done. I only need to get certainty on whether this actually works well in practice without needing to install extra packages or something like that.

**Comment by archbirdplus** [comment]
Downloading Zig12 was the least of my problems building Cubyz, probably thanks to `run.sh` doing that for me. It probably saves bandwidth from having me google why my homebrew Zig11 fails with a useless error.

Building Cubyz after applying commit 9978fd2 also helped me isolate the Zig crash. I suppose for normal use-cases, Cubyz-libs would work just fine. But it does make prototyping or using an unofficial Cubyz-libs more complicated.

**Comment by IntegratedQuantum** [comment]
> I suppose for normal use-cases, Cubyz-libs would work just fine. But it does make prototyping or using an unofficial Cubyz-libs more complicated.

That is true. But I found that it isn't too hard, since you can just change the entry in the build.zig.zon to import a local file.
It still requires a few extra steps sadly, like packaging the library into a tar.gz every time and clearing the `.seed` field, otherwise zig just keeps using the outdated version from the cache.

**Comment by archbirdplus** [comment]
Yeah as soon as I had to build it more than once I wrote a [Makefile](https://github.com/archbirdplus/Cubyz-libs/blob/macos-port/Makefile) for tar/gz'ing it. I wonder if you can do that in the `build.zig`?

**Comment by IntegratedQuantum** [comment]
It should be possible to add custom steps that execute arbitrary code. But honestly I don't know how use that in practice.
