### ISSUE TITLE
ANSI color codes are not supported on some windows terminals, causing random gibberish in the logs

### ISSUE THREAD

**Issue by IntegratedQuantum** [PixelGuys/Cubyz#143]
Is there a way to detect if the terminal supports ANSI color codes?

**Comment by zenith391** [comment]
Try `std.fs.getStdIo().supportsAnsiEscapeCodes()`

**Comment by IntegratedQuantum** [comment]
Thanks! Though I think you meant `std.io.getStdOut()`. `std.fs.getStdIo()` doesn't seem to exist.
