### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by lazynessmind** [PixelGuys/Cubyz#17]
The game is using almost 100% of my GPU with only the game open.
Its a RTX 2060

![image](https://user-images.githubusercontent.com/52864251/129502777-96842dc9-4a61-4db1-8f54-e019eb2eab8d.png)

55% to 70% on the main menu.

**Comment by IntegratedQuantum** [comment]
It's because vsync is disabled, which makes the game run at 5000 fps.
From now on(cbbcf507a67c0512b2fdc06fdf68b335f1ffe1b0) vsync is enabled by default.

But you still need to change it on your own in the settings. You can find it under `Opções/Gráficos/Vertical Synchronization`.

**Comment by lazynessmind** [comment]
:+1:
