### ISSUE TITLE
advanced physics effects

### ISSUE THREAD

**Issue by Pantyhose-X** [PixelGuys/Cubyz#265]
Global physics like [realistic minecraft](https://www.youtube.com/watch?v=kf7DAWcjmvQ). Physical effects., I'm in Cubyz when the wind blows in the wheat fields that's awesome , 
this should be an option: enabled or disabled

**Comment by IntegratedQuantum** [comment]
I never used unreal engine, so you have to clarify what physical effects you mean.
Is this just about wind, or are there other effects that you want?

**Comment by Pantyhose-X** [comment]
collision
Blast
Flow
Soft Body Dynamics

Just like https://developer.nvidia.com/physx-sdk

https://d29g4g2dyqv443.cloudfront.net/sites/default/files/akamai/omniverse/physX-gif-web.gif

https://developer.download.nvidia.com/video/physX/physX-force-field.gif

**Comment by IntegratedQuantum** [comment]
Oh, I see. Some of these are pretty expensive effects. let me just go through them:
- collision is already mentioned in #82
- Blast seems to be about realistic destruction of object, which I don't think makes much sense with the given scale of 1 voxel per meter. It's also unclear what do with the debris of a destruction like this.
- Flow - fluid/gas dynamics are definitely out of scope here. The scale of the world is too big to have any realistic fluid/gas behavior. I plan to use a simpler approach with per voxel fluid data: #62
- Soft Body Dynamics - not sure if it would fit the style of the game, but generally it would be kind of cool to have some soft-body entities. But it would require a ton of constraints.
- Wind - would probably be foremost a graphical feature, having arrows be influenced by wind might be interesting though.
