### ISSUE TITLE
GUI: Client VPS

### ISSUE THREAD

**Issue by Pantyhose-X** [PixelGuys/Cubyz#267]
> People want to have their own servers, but don't want to spend time tossing around vps providers and vps installation games.

### Client VPS GUI
Users wanting to run their own servers are very simple. 
* Enter server address vps password or one-time password (Authenticator) log in
* VPS GUI: In Cubyz client click on `me vps` send Select server address Games vps password Email. Scan the CQ code to pay. Your server is ready to run.
* Mods: Install Click on Browse Online Content to install to the vps server.

Of course they can deploy their own servers without using Cubyz's VPS! 
The client default built-in Cubyz's VPS is embedded over the network, which prevents other carrier vps from using the client vps gui. 

##  store website
vps admin Want to make mods for your own needs but don't know how to program. 

> Users post requests Prices
> Mods developers who want to make money
> Negotiate with users about the details of the mods' goals.  Determine approximate delivery time
> Finalize orders
> Both parties agree to fulfill the order.

 Avoid the dishonesty of both parties, Cubyz Team or third party guarantee
> When the "Guarantee OK" has reached the mods goal, the 
> When "Guaranteed OK" has not reached the mods goal, the developer is given one month to complete the delivery and the money is automatically refunded in full to the user.

**Comment by IntegratedQuantum** [comment]
I don't want to sell Virtual Servers to people and I also don't want to run a store.

> People want to have their own servers

People generally don't want their own servers. People just want to play with their friends.
In Cubyz you don't need a server to do that:
You can invite players directly to your singleplayer world. This is possible thanks to UDP holepunching.
