### ISSUE TITLE
Make crystals pass light through.

### ISSUE THREAD

**Issue by archbirdplus** [PixelGuys/Cubyz#289]
Real life giant crystals have a translucent effect. Impurities in them diffuse the light, preventing the image behind from being visible. Simply making their texture transparent would be invalid. However, some light does make its way through.

The proposal here is to treat crystals as a transparent glass for floodfill lightning calculations to simulate translucency, but have the texture itself opaque to prevent the image behind from showing through.

This proposal by itself allows using crystal material as a sunroof. If light scattering is implemented (#288), this would also let crystals get "stained" by the color of neighboring blocks, as happens in real life.

Here is an example of the intended effect:

![image](https://github.com/PixelGuys/Cubyz/assets/53286705/dd563ee0-52b2-41bc-bf3f-d6b0d9ac464d)

**Comment by IntegratedQuantum** [comment]
It's a nice idea, but in practice I don't think it would look nearly as nice as in the image.

**Comment by IntegratedQuantum** [comment]
![Screenshot at 2024-03-25 13-47-51](https://github.com/PixelGuys/Cubyz/assets/43880493/e38ceeee-9f1c-4248-b0ea-108062b7bc28)

**Comment by IntegratedQuantum** [comment]
I'm closing this since this is already possible in the engine, but there are no crystals where I would want to apply this(it doesn't really make much sense for crystals that glow on their own already in my opinion).
