### ISSUE TITLE
Anti-light

### ISSUE THREAD

**Issue by IntegratedQuantum** [PixelGuys/Cubyz#305]
An additionally light channel could be used to propagate anti-light.
When calculating the light value to be uploaded to the GPU, all other channel would be reduced by the anti-light value.
This would allow making biomes and rooms that seemingly swallow light.
Dynamic palette compression #156 would help a lot with this.

**Comment by IntegratedQuantum** [comment]
I tried implementing it, and it just looks like a bug.

**Comment by codemob-dev** [comment]
That's too bad, I was thinking about this as well.
