### ISSUE TITLE
If you leave render distance, anything you build gets deleted

### ISSUE THREAD

**Issue by du82** [PixelGuys/Cubyz#306]
1. Build a tall tower or anything that you can see from far away.
2. Move away from the structure, and it disappears
3. Move closer to where the structure was, and it never comes back
4. Any changes you made to that chunk were not saved and removed blocks come back

**Comment by IntegratedQuantum** [comment]
Sorry, the zig rewrite just isn't there yet.
This is already tracked in #80, so I'm closing this issue.
