### ISSUE TITLE
Larger Hotbar

### ISSUE THREAD

**Issue by careeoki** [PixelGuys/Cubyz#342]
A hotbar with 8 slots is really small (smaller than Minecraft’s, which is already quite small.) I find myself constantly having to swap items in and out of my hotbar when building with many blocks. 
If we want an even number, I think 12 would be good. 

Stardew Valley has the same amount, and it feels nice, with lots of room for tools, weapons, food, and some slots left over for building items.
![IMG_4196](https://github.com/PixelGuys/Cubyz/assets/122191047/19b5afe7-0b68-49b5-b2af-a170cacf2401)

**Comment by IntegratedQuantum** [comment]
Good idea. I think this would also work well with the other plans I have for the inventory.
