### ISSUE TITLE
Fences lose state when loaded from save

### ISSUE THREAD

**Issue by careeoki** [PixelGuys/Cubyz#354]
### Before leaving chunk
![image](https://github.com/PixelGuys/Cubyz/assets/122191047/f40c0c17-1ad0-4b58-bfb5-08055a0614e5)
### After leaving chunk
![image](https://github.com/PixelGuys/Cubyz/assets/122191047/9d0b9896-aca0-46fe-9554-267facbe0864)

**Comment by IntegratedQuantum** [comment]
I think the actual problem is that the fence state is never calculated on the server. The client only sends to the server that it placed a fence, but not it's orientation.
