### ISSUE TITLE
[Bug] Crafting items disappear when closing workbench

### ISSUE THREAD

**Issue by LordDeatHunter** [PixelGuys/Cubyz#37]
3 proposed solutions would be:
1. Block-storage system: Storing the items inside the block. This would also allow for other players to interact with said items.
2. Dropping the items to the ground, or on top of the workbench.
3. Returning the items back to the player.

**Comment by tillpp** [comment]
We are actually aware of this bug,hehe 
we are currently abusing it as our trashbin xD 

But yes,this needs fixing.

**Comment by LordDeatHunter** [comment]
Either way, it's better to have it here IMO. 2-3 "dev-abuse" bugs might not be much, but you can easily lose track of TODOs over time

**Comment by IntegratedQuantum** [comment]
For the inventory crafting option 3 is used, with fallback to option 2 if the inventory is full.
So I guess that would be the best option for the workbench as well.
But not until there is a proper trash bin or at least a chest to store trash outside the inventory
