### ISSUE TITLE
UI using block textures is too noisy

### ISSUE THREAD

**Issue by careeoki** [PixelGuys/Cubyz#373]
Here's the creative menu as it is now:
![image](https://github.com/PixelGuys/Cubyz/assets/122191047/04d4e07e-36a8-4b63-ab8e-ce80e741fe32)
It's a menu very dense with information, filled with different colours, materials, patterns, shapes, etc... The textured UI, being just as detailed as the items inside of it, is distracting from the actual important information.

Here's the creative menu with flat colours (not representative of any kind of final product):
![image](https://github.com/PixelGuys/Cubyz/assets/122191047/8d196f4e-c734-462a-b1d2-9e5a49112ae8)
You can see how much more the items "pop" out of the menu, and generally, it's much cleaner

Things to note:
No, adding the updated textures to the UI will not fix this. 

Of course, doing this removes a lot of character from the UI. I think the idea of the UI being made of real materials is a good one, just not this execution.

**Comment by IntegratedQuantum** [comment]
Would it maybe be enough to just make the slots opaque?
![Screenshot at 2024-05-20 10-38-09](https://github.com/PixelGuys/Cubyz/assets/43880493/5b51bf07-4132-4fc8-bfb9-541091aefa18)

**Comment by careeoki** [comment]
That would be good for now. If you commit that I can update the UI textures. 
There's other things I would want to see improved but those would be separate issues and are not too important now.

**Comment by IntegratedQuantum** [comment]
You can also change it yourself if you want, the textures for the item slots are in `assets/cubyz/ui/inventory`.

**Comment by careeoki** [comment]
Oh, I thought those were hardcoded. Don't worry, I can do it then.
