### ISSUE TITLE
UI is not pixel consistent

### ISSUE THREAD

**Issue by careeoki** [PixelGuys/Cubyz#378]
![image](https://github.com/PixelGuys/Cubyz/assets/122191047/ba9dfd32-38f0-4d8a-85ae-009f677647bf)
I recommend the items using the 4 x 4 pixels, to match the UI, and also because using an odd number causes distortions at small scales
![image](https://github.com/PixelGuys/Cubyz/assets/122191047/b7dc07bb-f172-42fe-aac7-bd3c0d36de6e)

**Comment by IntegratedQuantum** [comment]
I also set the default window size of all the inventory windows to 0.75, otherwise the item slots would have been too big.

**Comment by careeoki** [comment]
Crafting button icon is still using the old scale.
![image](https://github.com/PixelGuys/Cubyz/assets/122191047/aef50a4e-95e3-4acf-8794-f3b170218d2e)
