### ISSUE TITLE
9-slice button textures

### ISSUE THREAD

**Issue by careeoki** [PixelGuys/Cubyz#379]
Would allow nice looking buttons with bold outlines.
![image](https://github.com/PixelGuys/Cubyz/assets/122191047/bba31f73-2a57-4251-8afc-a139435e56bf)
Also would prevent situations like this where pixels are abruptly cut off.

**Comment by IntegratedQuantum** [comment]
What do you mean by 9-slice?

**Comment by careeoki** [comment]
https://en.wikipedia.org/wiki/9-slice_scaling

**Comment by IntegratedQuantum** [comment]
Hmm, I think with a 9-slice texture you'd get the same problem, except the pixel cut off would be between the border and the center region.

**Comment by careeoki** [comment]
I'd like to make buttons like this. They would be untextured for the same reason as the item slots, as they would have text or icons on them.
![image](https://github.com/PixelGuys/Cubyz/assets/122191047/cf13d1ed-b5dc-46fc-ab29-52d49d0a5f17)

**Comment by IntegratedQuantum** [comment]
I personally would like to keep some pattern on the buttons, maybe something like the chalk texture.

But I could probably add a nine-slice texture for the outline that's overlaid onto a base texture, like wood or chalk.

**Comment by IntegratedQuantum** [comment]
Alright, that should give you some room to work with.
I also unhardcoded the button selection and pressed states, so you can change those as well.

**Comment by careeoki** [comment]
Oh, awesome, thanks!!
