### ISSUE TITLE
UI vignette looks bad

### ISSUE THREAD

**Issue by careeoki** [PixelGuys/Cubyz#380]
![image](https://github.com/PixelGuys/Cubyz/assets/122191047/66ba8486-46fb-4198-b860-08ee46aba83c)
Having a smooth, hi-res gradient on top of pixel art looks strange. I think a solid-coloured border would look much better and serve the same purpose.

**Comment by IntegratedQuantum** [comment]
Like this?
![Screenshot at 2024-05-21 21-29-53](https://github.com/PixelGuys/Cubyz/assets/43880493/7c4a14e4-8edc-4c60-b305-d944b2f1a858)
We could also keep the gradient with a lower resolution like this:
![Screenshot at 2024-05-21 21-29-32](https://github.com/PixelGuys/Cubyz/assets/43880493/db431bc8-68bb-4eae-a9c6-3e41d6efb0d5)

**Comment by careeoki** [comment]
Yes, like the first image. If it was around the outside of the window, not blocking the icons, that would be the best.

**Comment by IntegratedQuantum** [comment]
![Screenshot at 2024-05-22 10-28-39](https://github.com/PixelGuys/Cubyz/assets/43880493/d7473caa-6068-4fb0-ad00-6ba2133a4d70)
If I put it on the outside that makes it looks weird when there are two windows attached to each other.
Alternatively I could also move the items one pixels further in like this:

![Screenshot at 2024-05-22 10-33-33](https://github.com/PixelGuys/Cubyz/assets/43880493/4645a379-8e0a-4c0a-8fcc-0e20c4d35953)

**Comment by careeoki** [comment]
![image](https://github.com/PixelGuys/Cubyz/assets/122191047/826572bc-c175-4c82-a2ea-8cef8e1f853a)
This is what I would like to have. The icons are 7x7 (for a 1-pixel center) and the window_title is 9 pixels tall.
The border is opaque.
