### ISSUE TITLE
New name for Cubyz

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [PixelGuys/Cubyz#427]
l are opening up to suggestions for a new name for Cubyz. l feel the Voxel has to do to reach it's full potential. As a result, we are committed to this rebrand. New name candidates should not be taken by anything active, and we'd have to be careful with previous usage. Please verify this before putting a candidate forward. The criteria we are looking for is as follows:

* short
* interesting
* easy to (not mis)type

---
Kubli , KUBLI is mainly inspired by the [Lojban](https://en.wikipedia.org/wiki/Lojban) language word [is a cube/regular polyhedron/polygon of dimensions ](https://la-lojban.github.io/sutysisku/lojban/index.html#seskari=cnano&sisku=kubli&bangu=en&versio=masno)

canpa , CANPA is mainly inspired by the [Lojban](https://en.wikipedia.org/wiki/Lojban) language word [is a shovel/spade [bladed digging implement] for digging](https://la-lojban.github.io/sutysisku/lojban/index.html#seskari=cnano&sisku=canpa&bangu=en&versio=masno)

larcu, LARCU s mainly inspired by the [Lojban](https://en.wikipedia.org/wiki/Lojban) language word [is an art [creative application] of craft/skill (idea/activity).](https://la-lojban.github.io/sutysisku/lojban/index.html#seskari=fanva&sisku=larcu&bangu=en&versio=masno)

kunra , KUNRA is mainly inspired by the [Lojban](https://en.wikipedia.org/wiki/Lojban) language word [is/contains/is made from a mineral/ore of type/metal mined from location/lode/mine](https://la-lojban.github.io/sutysisku/lojban/index.html#seskari=cnano&sisku=kunra&bangu=en&versio=masno)

Calsle , CALSLE is mainly inspired by the [Lojban](https://en.wikipedia.org/wiki/Lojban) language word [meaning is a voxel of model/object](https://la-lojban.github.io/sutysisku/lojban/index.html#seskari=cnano&sisku=calsle&bangu=en&versio=masno)

---

Cltoq , CLTOQ is mainly inspired by the [Toaq](https://toaq.net/) language word [ is a cube.](https://toadua.uakci.space/#c%C4%B1toq)

Baılea, BAILEA is mainly inspired by the [Toaq](https://toaq.net/) language word [is the craft of](https://toadua.uakci.space/#ba%C4%B1lea)

---

Tsau, TSAU is mainly inspired by the [eberban](https://eberban.github.io/eberban/) language word
[is made/created/manufactured/crafted](https://eberban.github.io/eberban/web/dictionary.html#tsau)

Kelon, KELON is mainly inspired by the [eberban](https://eberban.github.io/eberban/) language word 
[is a box.](https://eberban.github.io/eberban/web/dictionary.html#kelon)
> A rigid typically rectangular container with or without a cover. Its volume is not only the walls but the volume between them.

**Comment by archbirdplus** [comment]
My criteria additionally would be the following:
- be easily searchable, not fighting anyone else for the top spot
- be easy to remember intuitively
- not sound like a generic startup name
Unfortunately, Cubyz already fits this perfectly 🤷

**Comment by OneAvargeCoder193** [comment]
I agree with archbirdplus

**Comment by OneAvargeCoder193** [comment]
Also, we already have a logo for cubyz, so at this point, i don't see the name being changed anytime soon.

**Comment by IntegratedQuantum** [comment]
There is one more important thing:
- The name should capture the identity of game

The identity is not well defined yet, which is why it's probably best to stick to Cubyz until then.

**Comment by archbirdplus** [comment]
The identity so far is a super fast voxel engine base for people to mod easily, and add their own flavor to. Cubyz reflects that very well.

**Comment by Weltspear** [comment]
I agree with @archbirdplus and I don't think a name change is necessary

**Comment by IntegratedQuantum** [comment]
Yeah, you are right, Cubyz already is a good name.
And even if we could (and I don't think we can) come up with a slightly better name, it wouldn't be worth the effort of renaming.
