### ISSUE TITLE
Show performance of threadpool tasks

### ISSUE THREAD

**Issue by archbirdplus** [PixelGuys/Cubyz#433]
Preferably split it up as well:
- chunkgen
- lighting
- whatever else

This would help optimizations.

**Comment by IntegratedQuantum** [comment]
What exactly would this show? Average time spent?

**Comment by archbirdplus** [comment]
Here's what I have so far. The µs/task stat is actually quite stable even without any averaging.
![image](https://github.com/PixelGuys/Cubyz/assets/53286705/002b16d4-c17b-4817-a0bb-0afdbdeb7c3e)

**Comment by archbirdplus** [comment]
Honestly, 1 millisecond per 32^3 is kind of ridiculous.

**Comment by IntegratedQuantum** [comment]
Yeah, and keep in mind there is two tasks per chunk, one for lighting/meshing and one for generation. I think lighting takes a big chunk of that combined time. That's why it might be more interesting to see the time per task. Maybe we can add a `getTaskId` to the VTable to handle these?

**Comment by archbirdplus** [comment]
My plan was just `enum TaskClass`.

**Comment by IntegratedQuantum** [comment]
Wouldn't this make adding new tasks more difficult?

**Comment by archbirdplus** [comment]
Findings:
![image](https://github.com/PixelGuys/Cubyz/assets/53286705/a47397f6-9e61-440c-a199-3ab667ec965b)
This is the version I am making a PR for.

**Comment by IntegratedQuantum** [comment]
fixed by #445
