### ISSUE TITLE
Add an average of x frames into the frame time graph.

### ISSUE THREAD

**Issue by IntegratedQuantum** [PixelGuys/Cubyz#438]
x=12 might be good, since it has many factors.

**Comment by archbirdplus** [comment]
Should it be an option, or just replace the current behavior? Should it update on every 12th frame as well to read better? Maybe the refresh rate should be based on time? How do other games implement it?

**Comment by IntegratedQuantum** [comment]
I would prefer if it is a second line in the graph, maybe with a different color.
I think it's very important to have both, to be able to see small lag spikes.
Te refresh can be a single frame, since there is no changing text in the graph.

**Comment by archbirdplus** [comment]
What do you mean by the last line?
> Te refresh can be a single frame, since there is no changing text in the graph.

**Comment by IntegratedQuantum** [comment]
It's a line graph.
![Screenshot at 2024-06-06 08-42-27](https://github.com/PixelGuys/Cubyz/assets/43880493/c51f1171-c007-478e-bacc-a3eb180374f1)
I find it not at all difficult to read at high refresh rates.

**Comment by archbirdplus** [comment]
I took this issue to encompass all benchmarks. Particularly relevant for optimizing specific things, and #445 task perfs. To have a number to jot down and compare. Is this a separate issue or just #445?

The line graph is just impressionistic so its fine to have it update every frame.
Here's my graph by the way (idk if you want to support this):
<img width="268" alt="Screenshot 2024-06-05 at 23 45 39" src="https://github.com/PixelGuys/Cubyz/assets/53286705/cf1b0eb5-030d-44f5-b330-136ab54d0bd4">

**Comment by IntegratedQuantum** [comment]
No, this is a seperate issue, to make it easier to compare frametime, when there is a lot of jitter in the graph.

**Comment by IntegratedQuantum** [comment]
I am no longer convinced that this really is any useful.
