### ISSUE TITLE
mods: All minerals of the Earth

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [PixelGuys/Cubyz#446]
There are more than 6,000 minerals known to man.
I think it should be a separate github repository mods or built-in mods
Separate mods where people can submit ores crafting recipes.

ores Name: https://rruff.info/ima
ores image: https://rruff.info/about/about_general.php

I asked the site owner, can use rruff.info data.

But it must References text

`
Lafuente B, Downs R T, Yang H, Stone N (2015) The power of databases: the RRUFF project. In: Highlights in Mineralogical Crystallography, T Armbruster and R M Danisi, eds. Berlin, Germany, W. De Gruyter, pp 1-30
`

**Comment by IntegratedQuantum** [comment]
I will not add 6000 minerals to the base game, and I will not maintain any mods at this point.
If you want to make a mod with all the minerals of the earth, then please make your own repository.
I guess I could maintain a repository with a curated list of known addons/mods, but I won't make such a repository until there is at least on addon/mod with some new content.
