### ISSUE TITLE
Distributable linking

### ISSUE THREAD

**Issue by archbirdplus** [PixelGuys/Cubyz#460]
Cubyz is actually really poorly set up for building to distribute on mac. I suspect the same might be true for linux as well.

Currently, Cubyzig has the following rpaths:
```
     path /Users/USER/.cache/zig/p/12204ba799cc74baeec8284b8a22cd0b597b58d5fa32c6eac999635fdc1834c950fc/lib (offset 12)
     path /usr/local/GL/lib (offset 12)
     path /Users/USER/Cubyz/Library (offset 12)
     path /opt/homebrew/Cellar/libx11/1.8.9/lib (offset 12)
     path /Users/USER/.cache/zig/p/12204ba799cc74baeec8284b8a22cd0b597b58d5fa32c6eac999635fdc1834c950fc/lib (offset 12)
```

There are a number of problems:
- cubyz_deps is listed twice (it shouldn't be at all, since it's a static library).
- The Library path is nonsensical because Zig evaluated it at build-time instead of runtime.
- Cubyz should link against XQuartz X11, not homebrew.
- X11 doesn't need an RPATH.

So, at present, every single rpath is just plain invalid for distribution.

Ideally, the rpaths would just be the following:
```
    path @executable_path/../Library (if app bundle)
    path /usr/local/GL/lib (if local build)
```

But I'm not sure if this is even possible within Zig build! Zig seems to discourage linking libraries by their paths alone (demanding an entire compile step or just a query to pkgconfig), and forcefully includes some (incorrect) rpath.

**Comment by archbirdplus** [comment]
This might be Zig's Build library rebelling against us doing something that violates its standards of beauty. It's standards are too idealistic though.

It may be possible to link these things manually by abusing commandline Zig, which might have fine-grained rpath support - https://github.com/ziglang/zig/issues/5827. The commandline linker might not be exposed though.

**Comment by archbirdplus** [comment]
Of course, I could just `install_name_tool`/`patchelf` in the ci script.

**Comment by IntegratedQuantum** [comment]
Is it really a problem to have unused stuff in the rpaths?

**Comment by archbirdplus** [comment]
That looks like it!

It's not necessarily wrong, but it's not necessary. It also leaks my username from my builds. And also it is wrong. So I might as well fix as many of these together as I can.

**Comment by archbirdplus** [comment]
Thanks for the `root_module.addRPathSpecial`, I never would have found it (`root_module` doesn't even appear in Zig docs).
I also found us a `exe.addObjectFile` for cubyz_deps. Since it turns out X11 doesn't need to be linked either, I removed it in my PR.
