### ISSUE TITLE
Replace f32 with f64 in terrain generation

### ISSUE THREAD

**Issue by OneAvargeCoder193** [PixelGuys/Cubyz#476]
![Screenshot 2024-06-16 145521](https://github.com/PixelGuys/Cubyz/assets/85588535/6bd3725d-ab2c-4ac3-b543-19f341cc1927)
It causes very buggy terrain far out

**Comment by IntegratedQuantum** [comment]
I think a better solution would be to only use relative coordinates, or maybe store some fixed point format.

related issue: #311

**Comment by OneAvargeCoder193** [comment]
For example, 1 billion blocks out, there is already an inaccuracy of 64 blocks

**Comment by OneAvargeCoder193** [comment]
> I think a better solution would be to only use relative coordinates, or maybe store some fixed point format.
> 
> related issue: #311

We could store a u64 fixed point, which could get all the way up to the integer limit but also would have 1 over the integer limit precision

**Comment by IntegratedQuantum** [comment]
We could also try a i32 fixed point, where the top 16 bits are cut off.
Then only for seeds and stuff we'd get the top 16 bits from another variable.

**Comment by IntegratedQuantum** [comment]
And in some places, like the biome generation, it might just be enough to use a normal i32 with one block of precision

**Comment by ITR13** [comment]
> I think a better solution would be to only use relative coordinates, or maybe store some fixed point format.

Using relative coordinates would also fix a similar issue in collision detection.
Currently both collision detection and biome generation crash near/at the integer limit.

**Comment by IntegratedQuantum** [comment]
I don't think buggy farlands are something that we should bother about.
Honestly it might even be considered more of a feature than a bug.
