### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Anthoulis** [PixelGuys/Cubyz#49]
- [X] Crosshair + is visible when openning settings and in my example is over Fog
- [x] At night some settings are not visible because of low light and colour selection
- [x] I have a very good pc hardware but when I increase Render Distance and LOD Factor the game crushes and doesn't respond
- [X] Mouse sensitivity is an important setting as well
![Settings](https://user-images.githubusercontent.com/32645363/154822053-fdbbb1bc-aa7d-479b-bc43-0770080a97be.PNG)

**Comment by IntegratedQuantum** [comment]
Thank you for taking the time to write down a list of problems and bugs.
I'll look into them before the next release.

**Comment by IntegratedQuantum** [comment]
All done. Thanks again for finding these.
The contrast issue in the graphics settings was in the game for a long time(1¹⁄₂ years) and probably wouldn't have been found for a long time without you.
