### ISSUE TITLE
loot icons

### ISSUE THREAD

**Issue by Anthoulis** [PixelGuys/Cubyz#50]
In some cases when you are looting from low to high the loot stays mid air. They only fall when you destroy all nearby blocks, I assume it has something to do with the hitbox and the method used to fall.
Another thing I noticed is that sometimes when I destroy a cube of any material and falls, when it lands on a stone cube, the icon of the loot falls in to the stone making the icon visually not seen but still able to collect it if you go near it.
![item stuck on air](https://user-images.githubusercontent.com/32645363/155034792-0b78450f-21d4-401b-8ef3-df592faaf637.PNG)

**Comment by IntegratedQuantum** [comment]
Yeah, they tend to get stuck in blocks fairly often.
Whether it be underground or just on the sides of another block.
I'll work on it before the next release.
