### ISSUE TITLE
Make walk speed faster

### ISSUE THREAD

**Issue by careeoki** [PixelGuys/Cubyz#505]
Currently, it feels more like sneaking in Minecraft than actual walking.

**Comment by IntegratedQuantum** [comment]
Can you check if it still feels too slow?
It should now be accurately at 4 m/s(minecraft walking is at 4.3), 8 m/s for sprinting(minecraft sprinting is at 5.6, up to 7.1 when jumping).

**Comment by careeoki** [comment]
Yeah, it feels good now.
