### ISSUE TITLE
falling from high altitude, hp to 0 but game continues with no death

### ISSUE THREAD

**Issue by Anthoulis** [PixelGuys/Cubyz#51]
Falling from high altitude makes hp go to 0, gets the screen red but the player doesn't die, there is no death or respawn.
![no life but game still plays](https://user-images.githubusercontent.com/32645363/154822265-2ee9a21e-24c5-4729-a6ca-a2272ac0a421.PNG)

**Comment by IntegratedQuantum** [comment]
There is no death mechanic yet.
I probably won't work on that until there is an actual reason die(like hostile mobs).
Until then death would be just annoying(especially for testing).

**Comment by IntegratedQuantum** [comment]
I implemented a basic respawn mechanic while working on multiplayer.
