### ISSUE TITLE
Cave structures generating on the surface

### ISSUE THREAD

**Issue by careeoki** [PixelGuys/Cubyz#547]
A fix doable right now is just to set the max_height of the biome lower. But every cave entrance being the same is boring.
This only seems to affect certain structures, maybe? Stalagmites and ground_patches in these examples. I haven't seen misplaced boulders or stone forest trees.
![image](https://github.com/PixelGuys/Cubyz/assets/122191047/436e708e-a1c1-4379-ac9c-0d2592dcb284)
![image](https://github.com/PixelGuys/Cubyz/assets/122191047/b377ad4e-fc50-4a9f-8258-469fe15398ff)

**Comment by IntegratedQuantum** [comment]
Stalagmites (and crystals) are generated outside of the structure system, which explain why they behave differently.
Ground patches are a different problem though, I suspect it's just continuing an underground ground patch on the surface here.
