### ISSUE TITLE
Cannot place a block on the sides of a block you are walking into

### ISSUE THREAD

**Issue by OneAvargeCoder193** [PixelGuys/Cubyz#549]
I think the game thinks it cant place it because it is in the players hitbox

**Comment by OneAvargeCoder193** [comment]
This also happens in a situation like this

**Comment by OneAvargeCoder193** [comment]
It also still happens after you stop walking into the block
I think what is happening in this case is the player is still very slightly in the block

**Comment by OneAvargeCoder193** [comment]
This is another example of when it happens
![Screenshot 2024-07-07 114225](https://github.com/PixelGuys/Cubyz/assets/85588535/b9f92031-bd97-4d9e-a8ff-9e72e1d14c0a)
The players hitbox goes through the corner

**Comment by IntegratedQuantum** [comment]
It's checking the wrong hitbox when placing
