### ISSUE TITLE
Can we build Cubyz on android?

### ISSUE THREAD

**Issue by codingwatching** [PixelGuys/Cubyz#55]
Hi there
Could you please support Cubyz to run on an android device?
Thank you so much!

**Comment by IntegratedQuantum** [comment]
I want to support as many platforms as possible, but it's too soon for that.

1. Cubyz isn't much of a game yet, there is still a lot of stuff missing.
And honestly in a few years I'd rather have a fun game for PC than a fancy tech demo that runs on all devices.
2. I'm kind of having problems with java right now(the garbage collector is causing lag spikes) and I might end up switching the language. Now if I had everything ported to android already that would make it a lot harder to switch.
3. Supporting android is more than just "implement it once and then forget about it". Once it's there I have to put effort in maintaining and testing it. For example I'd have to make sure new graphics features run in OpenGL and OpenGL ES depending on the platform. And that early in development I might throw the feature out entirely a few updates later.

**Comment by codingwatching** [comment]
Hi @IntegratedQuantum 
Thank you so much, Have a nice day!

**Comment by Zig-Rust-Odin** [comment]
postmarketOS should be able to run it directly but, the game interface should need to be adaptive and maybe a joystick 🎮 to operate the game
[postmarketOS](https://postmarketos.org/) is a mobile linux distribution that can do everything linux can do.

**Comment by IntegratedQuantum** [comment]
I doubt that. Did you actually try to run it on PostmarketOS?

**Comment by IntegratedQuantum** [comment]
I have decided against this. Cubyz will remain primarily a PC game and I don't think I want to bother with the extra burden of supporting mobile platforms.

However the open source nature of the game makes it possible for anyone to create a third party android version of Cubyz.
