### ISSUE TITLE
Vertical Rail

### ISSUE THREAD

**Issue by jujubeja** [PixelGuys/Cubyz#559]
Vertical Rail implementation roller coaster
Example Video: https://youtu.be/Ps8EvrLu02Y?t=37 [![IMAGE ALT TEXT HERE](https://user-images.githubusercontent.com/42504385/223293452-c453e99a-3b2b-4494-ba6e-a72f3cc16fad.png) ](https://youtu.be/Ps8EvrLu02Y?t=37)

[![IMAGE ALT TEXT HERE](https://camo.githubusercontent.com/62e39ab07ac8452fa7e28379d27b1ed4b4fe8028fdfe3dc2c806bd753ea5d32c/68747470733a2f2f72696465656e7465727461696e6d656e742e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032312f30342f3332305f45585f4c6966742e6a7067)](https://youtu.be/Ps8EvrLu02Y?t=37)

**Comment by IntegratedQuantum** [comment]
I don't see a place for roller coasters in the base game. It seems better suited for a mod.
Now vertical rails on their own still be added as a by-product of #72, but I wouldn't bet on it.
