### ISSUE TITLE
Jumping into a block with a block above your head allows you to get into 1 block gaps

### ISSUE THREAD

**Issue by ikabod-kee** [PixelGuys/Cubyz#560]
https://github.com/PixelGuys/Cubyz/assets/155805949/73b03aa4-f3d0-441a-bf4f-029936f164ac

**Comment by IntegratedQuantum** [comment]
It's hard to decide whether this is a bug or a feature.

**Comment by LinaPlusPlus** [comment]
only the fact the hitbox doesn't change is a bug
