### ISSUE TITLE
Gameplay trouble

### ISSUE THREAD

**Issue by Ygarr** [PixelGuys/Cubyz#57]
Sometimes during the game or even at the start I stuck like on the screenshot and have no ability to return on ground surface
![image](https://user-images.githubusercontent.com/14309871/221212025-f41286e8-b8bb-4925-a67c-6bf738dfcf8e.png)

**Comment by IntegratedQuantum** [comment]
Yeah, that's a known issue caused by lag spikes.

Until this is fixed you can press `F` to toggle flying (basically like spectator mode in minecraft)

**Comment by IntegratedQuantum** [comment]
The zig rewrite no longer suffers from java's garbage collector lag spikes. Therefore this issue won't happen there.
