### ISSUE TITLE
Support for more modern mesh format(s)

### ISSUE THREAD

**Issue by jujubeja** [PixelGuys/Cubyz#642]
* [glTF](https://en.wikipedia.org/wiki/GlTF) (Khronos standard, alive)
* [COLLADA](https://en.wikipedia.org/wiki/COLLADA) (Khronos standard, old)
* [M3D](https://gitlab.com/bztsrc/model3d)

I personally recommend glTF

**Comment by IntegratedQuantum** [comment]
For now I would like to keep dependencies low and I think a simple, human-readable format such as obj #290 is perfect.

That being said it might make sense to consider other formats in the future.

**Comment by IntegratedQuantum** [comment]
obj is supported. I don't think it makes sense to support any other, more complicated formats, unless an artist working on the game or a popular addon asks for it, which you don't seem to be.
