### ISSUE TITLE
Play animations from a sprite sheet

### ISSUE THREAD

**Issue by careeoki** [PixelGuys/Cubyz#664]
I am working on a new animated water texture, which has 30 frames. Each animation frame has to be it's own file, so that's 30 different pngs, and then there needs to be absorption, reflectivity, and textureInfo for each frame, so that's 30+30+30+30=120 files for one block.

Individual files makes it really annoying to work on animations, and i don't have any way to automate the creation of these files regardless.

It would be much more convenient if animations could be loaded from one sprite sheet file (a vertical strip of all the frames)
And maybe textureInfo could be in the block json?

**Comment by IntegratedQuantum** [comment]
> And maybe textureInfo could be in the block json?

The textureInfo json exists to allow texturepacks to overwrite these parameter without modifying core block properties. I actually plan to extend the textureInfo in the future, so it also contains info on the number of animation frames and animation time to make those easier to configure.
