### ISSUE TITLE
Player keeps forwards momentum when sliding against block

### ISSUE THREAD

**Issue by ikabod-kee** [PixelGuys/Cubyz#676]
Not sure if intended. Here is a comparison between an old and new version.

https://github.com/user-attachments/assets/61308997-7641-4015-acc1-a1e14bad1b8b

**Comment by IntegratedQuantum** [comment]
This is not intended. Could this be an accidental side-effect of the refactoring in #663 @ITR13?

**Comment by ITR13** [comment]
Ah, yes, I know why it happens. Should be a quick fix.
