### ISSUE TITLE
map generation: galaxies

### ISSUE THREAD

**Issue by atlantis451** [PixelGuys/Cubyz#680]
I want to see 'Cubyz' pilot their own assembled spaceship, exploring and developing other planets.

- List of nearest galaxies https://en.wikipedia.org/wiki/List_of_nearest_galaxies
---

 space ship https://youtu.be/watch?v=8OrZX347MoE

---
### off-topic
https://exoplanetarchive.ipac.caltech.edu/ NASA confirmed planets
https://en.wikipedia.org/wiki/Observable_universe

youtube
[Size Comparison of the Universe](https://www.youtube.com/watch?v=134nAVodmp8)
[ABSOLUTE Size Comparison 2023 (FULL) 4K 60FPS 3D](https://www.youtube.com/watch?v=WocfYpjgb8M&t=5576s)

**Comment by IntegratedQuantum** [comment]
This does not fit the theme of the game.

**Comment by Weltspear** [comment]
> > This does not fit the theme of the game.
> 
> Just add some planets, he is still Voxel Sandbox Game, I don’t know why it is not in line with the theme of the game.
> 
> > If because 3D Chunks (→ There is no height or depth limit.)
> 
> The infinite height/depth, in my personal opinion, doesn't hold much significance. For example, regular users in Minecraft typically wouldn't build very deep underground.
> 
> The sky height can be set to the maximum visible range of the "static position" renderer.

This does not fit the theme of the game, because it is not focused on space exploration and adding such features would require a lot of effort which would be better used elsewhere.
