### ISSUE TITLE
Cave biomes seem to generate outside their desired height.

### ISSUE THREAD

**Issue by IntegratedQuantum** [PixelGuys/Cubyz#693]
Lava and crystal caves can appear near and above the surface at coordinates 12259 61194 160 in any world.

**Comment by ITR13** [comment]
Might be related to #475, or need the same solution (though I'm pretty sure there's already z ordering?)

**Comment by IntegratedQuantum** [comment]
#475 only applies when the terrain itself has a big height.

This is a different problem, likely introduced in bc1c1d6d922037afd1bdbf2c963c5689a4c19e7b.
