### ISSUE TITLE
Can't get Cubyz to run on my PC / How to get Cubyz to run on the GPU I want?

### ISSUE THREAD

**Issue by TheNewSector** [PixelGuys/Cubyz#694]
Specs:
-Windows 10
-Nvidia GeForce GTX 1050 
-Intel UHD Graphics 630
-Zig installation created by the game when it doesn't detect an existing version.

Currently, my game gives me this error upon starting run_windows.bat:

[error]: GLFW Error(65543): WGL: Driver does not support OpenGL version 4.6

I've spent a while troubleshooting, including installing the latest graphics drivers for my GPU, and looking at several threads online.

I've come the conclusion that my GTX 1050 should now support OpenGL 4.6 due to the driver update, and that reason this error persists is because my default GPU for Cubyz is set to the low-performance UHD card.

I've tried to fix this by going into my graphics settings, but whenever i browse into the Cubyz-master directory to change the games default GPU, all of the program files are hidden.

Due to the way Cubyz is structured, I'm not sure where or if the application that should run when I launch the game exists in the directory, or if it would even appear in the browse menu.

I'm currently stuck here. Any suggestions for how to fix this would be much appreciated, thanks.

**Comment by IntegratedQuantum** [comment]
> I'm not sure where or if the application that should run when I launch the game exists in the directory

The game executable is compiled on the first launch and then stored in `zig-out\bin\Cubyzig.exe`

**Comment by TheNewSector** [comment]
Didn't realize it already compiled it. I changed the setting to high performance and launched, worked first time. Thanks for responding so quickly btw
