### ISSUE TITLE
jumping up a fence pole sometimes teleports you in the wrong direction.

### ISSUE THREAD

**Issue by IntegratedQuantum** [PixelGuys/Cubyz#703]
https://github.com/user-attachments/assets/5de1adcf-e267-4012-850e-d1bdf46cad0e

@ITR13 could this be related to the physics changes you made recently?

**Comment by ITR13** [comment]
I can take a look at it, what specific block order is it?

**Comment by IntegratedQuantum** [comment]
Just two fences next to each. It only happens in one direction and when I jump it moves me one block in the opposite direction.
