### ISSUE TITLE
The game crashes when a player with an empty name joins.

### ISSUE THREAD

**Issue by IntegratedQuantum** [PixelGuys/Cubyz#704]

**Comment by ITR13** [comment]
> When you fix this, you should also make blank player names impossible.
That's tracked in #704

**Comment by ITR13** [comment]
> > That's tracked in #704
> 
> You mean this very issue?

My bad, thought this was 701 for some reason :<

**Comment by IntegratedQuantum** [comment]
What purpose does that serve, if you can just insert a space?

**Comment by IntegratedQuantum** [comment]
So what? That's not much different from using a camouflage skin.

Also in survival you probably won't see everyone from infinitely far away anyways.
A faction system like in Terraria could for example allow to only see your allies from a distance.
