### ISSUE TITLE
Cant craft

### ISSUE THREAD

**Issue by Cucuzacu** [PixelGuys/Cubyz#752]
I know this sound stupid, but i cant craft even planks!!!!! Is this a bug or i dont know how to use the crafting system??? pls help

**Comment by Cucuzacu** [comment]
thx. also, the game crashed when i pressed e while in the workbench menu, pls fix that

**Comment by IntegratedQuantum** [comment]
Inventory crafting is temporarily broken due to the changes of #643. It will be fixed soon (probably today even).

**Comment by Cucuzacu** [comment]
oh, another crash happens if u try to put the chisel in the crafting grid...

**Comment by Cucuzacu** [comment]
yea the crafting table is really broken
