### ISSUE TITLE
Carpet RotationMode

### ISSUE THREAD

**Issue by careeoki** [PixelGuys/Cubyz#775]
Functions like the Log mode, but allows you to place multiple carpets on a block, like the Torch mode. You should be able to carpet all faces of a block, including corners

You can test with this obj (renamed as an json so i can upload it):
[carpet.json](https://github.com/user-attachments/files/17759439/carpet.json)

**Comment by careeoki** [comment]
Sorry, yes, on walls and ceilings. Imagine it as moss or a crawling vines if that makes more sense
"Corners" is being able to fill in these gaps caused by only being able to place 1 carpet in a block.
![image](https://github.com/user-attachments/assets/b32125ff-789a-4244-9250-4b0fa246af3a)

**Comment by IntegratedQuantum** [comment]
Alright, that should be easy. Give me a minute.

**Comment by IntegratedQuantum** [comment]
Here you go (I couldn't be bothered to actually test with your carpet model):
![Screenshot at 2024-11-15 21-37-22](https://github.com/user-attachments/assets/d5b4f4a3-80bf-40de-a1c8-5fa7603582d5)

**Comment by careeoki** [comment]
Lol, that was quick. Thanks!
