### ISSUE TITLE
Textures are rotated incorrectly with Log and Carpet rotationMode

### ISSUE THREAD

**Issue by careeoki** [PixelGuys/Cubyz#787]
![387461962-78b882e9-eb94-4663-9722-e44aec4b0195](https://github.com/user-attachments/assets/61ee9032-b783-4ec0-9edc-874d8485e20b)

**Comment by IntegratedQuantum** [comment]
Is this really a problem for the log, I always thought it makes more sense, because it's more consistent with how the tree would fall:
![Screenshot at 2024-11-19 22-24-26](https://github.com/user-attachments/assets/2635b5eb-aadd-458f-ae1a-e2973f7eeb47)

**Comment by careeoki** [comment]
I think would be more consistent for building if it was the same orientation it each direction. Also it makes the lighting direction wrong.
