### ISSUE TITLE
World Creation Screen

### ISSUE THREAD

**Issue by IntegratedQuantum** [PixelGuys/Cubyz#79]
In the World Selection Screen there should be a button that leads to the world creation screen.

There the player should be given the opportunity to choose a name.

When creating the world a few files need to be created. And then the world can be opened just like in the code for the world selection screen.

**Comment by archbirdplus** [comment]
There does not seem to be documentation about what happens in a save file.

Currently, other than some duplicated assets, it looks like `saves/Development` just contains a `world.dat` and maybe `generatorSettings.json`. Besides the inability to actually save the placed blocks, isn't creating a new world just adding these files?

In other words, is contributing to this issue as simple as adding a button to write these few files?

**Comment by IntegratedQuantum** [comment]
Yeah, basically.
