### ISSUE TITLE
Resources Needed

### ISSUE THREAD

**Issue by IntegratedQuantum** [PixelGuys/Cubyz#8]
This is a list of all assets(textures, models, sound/music) Cubyz already has or still needs.
Make sure to check the [style restrictions](https://github.com/PixelGuys/Cubyz/blob/master/README.md#textures) of our textures before contributing.
If existing, the current version is shown.
Many textures on this list are only placeholders and need to be remade.

If you want to create one of them, comment on this issue or do so on our discord server.
**The general format of the textures is 16×16** (apart from special models)**. No other resolution will be accepted.**

Notice: This list only contains things that are already in the game. If you want to create a new item/block/entity, feel free to suggest it here on github or on our discord server. New suggestions are always welcome!

# Textures
## Blocks
(Temporal) Image | Name
-|-
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/cactus.png"> | <ul><li>[X] Cactus</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/coal_ore.png"> | <ul><li>[X] Coal Ore</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/cobblestone.png"> | <ul><li>[ ] Cobblestone</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/diamond_ore.png"> | <ul><li>[X] Diamond Ore</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/glass.png"> | <ul><li>[ ] Glass(and Colored Glass)</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/grass.png"> | <ul><li>[ ] Grass (on soil)</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/grass_herb.png" style="width:64;image-rendering:pixelated;"> | <ul><li>[ ] Grass (vegetation)</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/gravel.png"> | <ul><li>[ ] Gravel</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/ice.png"> | <ul><li>[X] Ice</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/iron_ore.png"> | <ul><li>[X] Iron Ore</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/lava.png"> | <ul><li>[ ] Lava</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/mossy_cobblestone.png"> | <ul><li>[ ] Mossy Cobblestone</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/oak_leaves.png"> | <ul><li>[X] Oak Leaves</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/oak_leaves_transparent.png"> | <ul><li>[X] Oak Leaves (transparent)</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/oak_log.png"> | <ul><li>[X] Oak Log</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/oak_planks.png"> | <ul><li>[X] Oak Planks</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/oak_top.png"> | <ul><li>[X] Oak Top</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/sand.png"> | <ul><li>[X] Sand</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/snow.png"> | <ul><li>[ ] Snow</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/snow_grass.png"> | <ul><li>[ ] Snow (on soil)</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/soil.png"> | <ul><li>[ ] Soil</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/stone.png"> | <ul><li>[ ] Stone</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/torch.png">| <ul><li>[X] Torch</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/undefined.png"> | <ul><li>[X] Undefined</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/water.png"> | <ul><li>[X] Water</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/blocks/textures/workbench.png"> | <ul><li>[X] Workbench</li></ul>
## Items
(Temporal) Image | Name
-|-
![Apple](https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/items/textures/food/apple.png) | <ul><li>[X] Apple</li></ul>
![Coal](https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/items/textures/materials/coal.png) | <ul><li>[ ] Coal</li></ul>
![Diamond](https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/items/textures/materials/diamond.png) | <ul><li>[ ] Diamond</li></ul>
![Raw Meat](https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/items/textures/food/raw_meat.png) | <ul><li>[ ] Raw Meat</li></ul>
![Stick](https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/items/textures/materials/stick.png) | <ul><li>[ ] Stick</li></ul>

## Entities
(Temporal) Image | Name
-|-
![Pig](https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/entities/textures/pig.png) | <ul><li>[ ] Pig</li></ul>
## Other
(Temporal) Image | Name
-|-
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/crosshair.png"> | <ul><li>[ ] Crosshair</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/breaking/0.png"> | <ul><li>[ ] Breaking animation (0)</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/breaking/1.png"> | <ul><li>[ ] Breaking animation (1)</li></ul>
### Inventory
(Temporal) Image | Name
-|-
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/guis/inventory/inventory_slot.png"> | <ul><li>[X] Inventory Slot</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/guis/inventory/selected_slot.png" width="64"> | <ul><li>[X] Inventory Slot (selection overlay)</li></ul>
### Status Bars
Beginning Empty | Middle Empty | End Emtpy | Beginning Full | Middle Full | End Full | Crack | Icon | Name
-|-|-|-|-|-|-|-|-
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/health_bar_beg_empty.png"> | <img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/health_bar_mid_empty.png"> | <img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/health_bar_end_empty.png"> | <img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/health_bar_beg_full.png"> | <img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/health_bar_mid_full.png"> | <img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/health_bar_end_full.png"> | <img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/health_bar_mid_half.png"> | <img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/health_bar_icon.png"> | <ul><li>[ ] Health Bar</li></ul>
<img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/hunger_bar_beg_empty.png"> | <img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/hunger_bar_mid_empty.png"> | <img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/hunger_bar_end_empty.png"> | <img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/hunger_bar_beg_full.png"> | <img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/hunger_bar_mid_full.png"> | <img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/hunger_bar_end_full.png"> | <img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/hunger_bar_mid_half.png"> | <img src="https://raw.githubusercontent.com/PixelGuys/Cubyz/master/assets/cubyz/textures/hunger_bar_icon.png"> | <ul><li>[ ] Hunger Bar</li></ul>

# 3D-Models
## Block Models
- [ ] Cube with all faces the same texture
- [X] Cube with all sides the same texture
- [ ] Cube with all faces different
- [X] Torch
- [X] Fence
- [ ] Pillars
- [ ] Doors
- [ ] Lever
- [ ] Button
- [ ] Chest
- [ ] Grass model
- [ ] Player Model
- [X] Quadruped models
- [ ] Stellar Body model (as a torus)

# Sounds and Music
## Music
- [ ] Game music
## Sounds
- [ ] Sound effects for everything

**Comment by HalfOfaSnack** [comment]
![cobblestone](https://user-images.githubusercontent.com/94792387/142765858-55b2fc50-8d6a-4631-8895-ab56c26bcd3d.png)
![gravel](https://user-images.githubusercontent.com/94792387/142765860-0d0916ab-1498-4562-b668-fb950cd88fed.png)
![Stone](https://user-images.githubusercontent.com/94792387/142765861-6795dbab-98d4-40ef-b403-0d63fb074e68.png)

The textures were chosed on basis and inspired/made to fit the dirt/grass block a bit better. Specifically made referencing the rocky hills biome (stone, gravel and cobblestone). Stone and cobblestone were made to fit eachother and the art desicions that were made begind the dirt block

**Comment by KingPork** [comment]
![pig](https://user-images.githubusercontent.com/88781103/142919891-315d83cd-2967-4714-962b-f8d73d5c5c59.png)

Pig

**Comment by KingPork** [comment]
![pig](https://user-images.githubusercontent.com/88781103/143088595-11c4cb24-a943-480c-9368-46fa91343338.png)
Pig

**Comment by KingPork** [comment]
![pig](https://user-images.githubusercontent.com/88781103/143090215-5a02a715-a612-4537-a893-b4adcfee862e.png)
Pig 2

**Comment by KingPork** [comment]
![pig](https://user-images.githubusercontent.com/88781103/143093631-2f369bb4-7b1c-4135-bcdf-dfd906dbd8c5.png)
Pig 3

**Comment by KingPork** [comment]
![pig](https://user-images.githubusercontent.com/88781103/143130654-f1694b04-8b9c-460f-80f4-403208ba6f21.png)
Pig 4

Should be correctly mapped now, at least I think so

**Comment by Tim7900** [comment]
[CubyzPlayer.zip](https://github.com/PixelGuys/Cubyz/files/7645751/CubyzPlayer.zip)

**Comment by Tim7900** [comment]
Her
![Meat](https://user-images.githubusercontent.com/85207005/145919517-68c1844d-2846-4552-8c57-e13b2f118324.png)
e

**Comment by Tim7900** [comment]
Hear
![Heart](https://user-images.githubusercontent.com/85207005/145920603-0a9df3b6-2ba5-46ef-ac5c-c97cde04bc27.png)
t

**Comment by IntegratedQuantum** [comment]
This issue is too outdated, too big and too imprecise.
