### ISSUE TITLE
Add an error notification window

### ISSUE THREAD

**Issue by IntegratedQuantum** [PixelGuys/Cubyz#810]
This could be used to for example display connection errors when trying to connect to a multiplayer server
related: #809 

This should be relatively simple to do, you just need to add a new window that renders a single label and add a global function to modify the contained string.

**Comment by somanshurath** [comment]
![Screenshot from 2024-12-04 22-22-06](https://github.com/user-attachments/assets/4e6cdb7e-88d5-49d5-8a1c-d303c3fae993)
something along these lines?

**Comment by IntegratedQuantum** [comment]
Yeah, but maybe just leave out "Notification" and red "Error" texts.

An extra "Ok" or "Acknowledge" button that closes the window might also be nice.
Just so the user knows that this message won't go away automatically.
