### ISSUE TITLE
Lava is blue and green from inside when the player is inside of a block

### ISSUE THREAD

**Issue by Moonyol** [PixelGuys/Cubyz#858]
Bloom off
![image](https://github.com/user-attachments/assets/8b4251e1-908e-47d7-9475-9bbaf8cba44e)

Bloom on
![image](https://github.com/user-attachments/assets/e9ea8ea2-b760-4935-a71d-e90eb880ed8e)

**Comment by IntegratedQuantum** [comment]
This is a side effect of how volumetric fog is calculated and unfixable.
For lava it would be fixed by #801.
For other transparent blocks it could be fixed on intel and nvidia hardware with #817.
