### ISSUE TITLE
Squares near water

### ISSUE THREAD

**Issue by Moonyol** [PixelGuys/Cubyz#861]
https://github.com/user-attachments/assets/d443c540-be97-4e47-878d-cb22eb84db68

https://github.com/user-attachments/assets/7782bb25-88a3-4994-83a3-8e02f2c77956

I've only seen them near water and there's a blue one at the end of the 1st video. I've seen one that wasn't square before but it might've had a different cause.

**Comment by IntegratedQuantum** [comment]
The video is broken for me:
![Screenshot at 2024-12-29 19-04-37](https://github.com/user-attachments/assets/7360169c-9f39-45ba-94b0-efd4643c7d65)
I even tried updating firefox.

**Comment by IntegratedQuantum** [comment]
Ah yes, these are T-junction pixel errors #92, amplified by bloom and fog.
