### ISSUE TITLE
Different directory for config

### ISSUE THREAD

**Issue by Moonyol** [PixelGuys/Cubyz#862]
On linux use ~/.config/cubyz instead of ~/.cubyz because it prevents putting files in the home directory

**Comment by IntegratedQuantum** [comment]
What linux distro do you use that has this problem? Because it works fine for me.
And many other games, like minecraft, put their stuff into the home directory on linux too.

**Comment by Moonyol** [comment]
Mint, I meant that it should be in the config folder because it only configures things

**Comment by IntegratedQuantum** [comment]
The same folder will also contain saves, the game executables and other things in the future once the launcher is done.
